# Generated by Codex on 2026-04-16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tracking", "0002_safezone"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppLimit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("package_name", models.CharField(max_length=255)),
                ("app_name", models.CharField(max_length=120)),
                ("daily_limit_minutes", models.PositiveIntegerField(default=60)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="app_limits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["app_name", "package_name"],
                "unique_together": {("child", "package_name")},
            },
        ),
        migrations.CreateModel(
            name="DeviceDailySummary",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("usage_date", models.DateField()),
                ("total_minutes", models.PositiveIntegerField(default=0)),
                ("over_limit_apps", models.PositiveIntegerField(default=0)),
                ("synced_at", models.DateTimeField(auto_now=True)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_usage_summaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-usage_date"],
                "unique_together": {("child", "usage_date")},
            },
        ),
        migrations.CreateModel(
            name="DeviceStatus",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("device_name", models.CharField(blank=True, max_length=120)),
                ("manufacturer", models.CharField(blank=True, max_length=120)),
                ("model", models.CharField(blank=True, max_length=120)),
                ("platform", models.CharField(blank=True, max_length=32)),
                ("os_version", models.CharField(blank=True, max_length=64)),
                ("timezone", models.CharField(blank=True, max_length=64)),
                ("battery", models.IntegerField(blank=True, null=True)),
                ("charging", models.BooleanField(default=False)),
                ("usage_access_granted", models.BooleanField(default=False)),
                ("synced_at", models.DateTimeField(auto_now=True)),
                (
                    "child",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_status",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AppUsageSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("usage_date", models.DateField()),
                ("package_name", models.CharField(max_length=255)),
                ("app_name", models.CharField(max_length=120)),
                ("usage_minutes", models.PositiveIntegerField(default=0)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="app_usage_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-usage_date", "-usage_minutes", "app_name"],
                "unique_together": {("child", "usage_date", "package_name")},
            },
        ),
    ]
