# Generated by Django 5.0.6 on 2026-04-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_alert_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('battery_low', 'Battery Low'), ('safe_zone_exit', 'Safe Zone Exit'), ('sos', 'SOS'), ('chat_message', 'Chat Message'), ('task_assigned', 'Task Assigned')], max_length=32),
        ),
    ]
