# Generated by Django 5.0.6 on 2026-04-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_add_sos_chat_task_alert_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotedevicecommand',
            name='command_type',
            field=models.CharField(choices=[('loud', 'Loud'), ('loud_stop', 'Loud Stop'), ('around_start', 'Around Start'), ('around_stop', 'Around Stop')], max_length=32),
        ),
    ]
