# Generated by Django 5.0.6 on 2026-04-20 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0009_locationupdate_charging'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotedevicecommand',
            name='command_type',
            field=models.CharField(choices=[('loud', 'Loud'), ('loud_stop', 'Loud Stop'), ('around_start', 'Around Start'), ('around_stop', 'Around Stop'), ('sync_blocked_apps', 'Sync Blocked Apps')], max_length=32),
        ),
        migrations.CreateModel(
            name='BlockedApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=255)),
                ('app_name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_apps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['app_name'],
                'unique_together': {('child', 'package_name')},
            },
        ),
    ]
